eliezer-souza/codeet

libs/domain/src/index.ts
libs/domain/src/modules/auth/commands/auth.command.ts
libs/domain/src/shared/prisma-client.ts
package.json
yarn.lock

- feat(auth): creating auth module
- feat(auth.command): encrypting the password

feat(auth): creating auth module

---

apps/codeet-next/pages/index.tsx
libs/domain/src/index.ts
libs/domain/src/modules/auth/commands/auth.command.ts
libs/domain/src/modules/domain.spec.ts
libs/domain/src/modules/domain.ts
libs/domain/src/modules/event/commands/event.command.ts
libs/domain/src/modules/group/commands/group.command.ts
libs/domain/src/modules/user/commands/user.command.ts
libs/domain/src/shared/command.ts

feat(domain): Creating User, Group and Event domains

feat(domain): creating User, Group and Event domains

---

libs/domain/src/modules/auth/commands/auth.command.ts

feat(auth-command): add validations in schemas

feat(auth-command): add validations in schemas

---

libs/ui/src/components/icon/icon.css.ts
package.json
yarn.lock

feat(icon): adding icon component

feat(icon): adding icon component

---

apps/codeet-next/pages/_app.tsx
apps/codeet-next/pages/index.tsx
libs/ui/src/components/icon/icon.css.ts
libs/ui/src/components/icon/index.ts
libs/ui/src/components/index.ts
libs/ui/src/components/input/input.css.ts

- feat(input): creating input component
- fix(icon): moving file icon function

feat(input): creating input component

---

apps/codeet-next/pages/index.tsx
libs/ui/src/components/input/input.css.ts

feat(input): creating label input component

feat(input): creating label input  component

---

apps/codeet-next/pages/_app.tsx
libs/ui/src/components/button/button.css.ts
libs/ui/src/components/input/input.css.ts

- feat(font): adding font family

feat(font): adding font family

---

apps/codeet-next/components/group-card.tsx
libs/domain/src/shared/command.ts

- fix(command): changing validationSchema

fix(command): changing validationSchema

---

.husky/commit-msg
.husky/prepare-commit-msg
commitlint.config.js
package.json
yarn.lock

- chore: add commitlint and husky
- chore(package): adding cz-conventional-changelog

chore(package): adding cz-conventional-changelog

---

apps/codeet-next/app/(events)/events/page.tsx
apps/codeet-next/app/(landing)/page.tsx
apps/codeet-next/app/layout.tsx
apps/codeet-next/components/event-card.tsx
apps/codeet-next/components/group-card.tsx

feat(events): creating events page

feat(events): creating events page

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/components/back.tsx
apps/codeet-next/components/event-card.tsx
apps/codeet-next/components/member-card.tsx
libs/domain/src/modules/event/commands/event.command.ts

- feat(event-information): creating event information page

feat(event-information): creating event information page

---

apps/codeet-next/next.config.js

- feat(next.config): adding serverComponentsExternalPackages

feat(next.config): adding serverComponentsExternalPackages

---

prisma/schema.prisma

Changing client generator to support different targets

feat(prisma-client): support target

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/app/(events)/events/page.tsx
apps/codeet-next/app/(groups)/groups/page.tsx
apps/codeet-next/app/(landing)/page.tsx
apps/codeet-next/app/layout.tsx

- chore(project): adjusting css

chore(project): adjusting css

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/app/(user)/user/[userId]/profile/page.tsx
apps/codeet-next/lib/auth.ts
libs/domain/src/modules/event/commands/event.command.ts
libs/domain/src/modules/user/commands/user.command.ts
prisma/migrations/20221120035312_external_id/migration.sql
prisma/schema.prisma

- feat(schema): adding externalId

feat(schema): adding externalId

---

apps/codeet-next/lib/auth.ts

- fix(schema): changing externalId

fix(schema): changing externalId

---

apps/codeet-next/app/layout.tsx
apps/codeet-next/next.config.js
package.json
yarn.lock

feat(axiom): adding reportWebVitals of axiom

feat(axiom): adding reportWebVitals of axiom

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/app/layout.tsx
apps/codeet-next/components/attend-event.tsx
apps/codeet-next/components/leave-event.tsx
apps/codeet-next/pages/api/events/[eventId]/attend-event.ts
apps/codeet-next/pages/api/events/[eventId]/leave-event.ts
libs/domain/src/modules/event/commands/event.command.ts

- feat(event): adding AttendEvent and LeaveEvent features

feat(event): adding AttendEvent and LeaveEvent features

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/app/layout.tsx
apps/codeet-next/components/attend-event.tsx
apps/codeet-next/components/react-query-wrapper.tsx
apps/codeet-next/components/session-wrapper.tsx
libs/domain/src/modules/event/commands/event.command.ts

- fix(events): adding redirect when user is not authenticated

fix(events): adding redirect when user is not authenticated

---

apps/codeet-next/app/(events)/events/[eventId]/page.tsx
apps/codeet-next/components/participants-card.tsx
apps/codeet-next/components/ui/dropdown.tsx
apps/codeet-next/components/ui/scrollarea.tsx
package.json
yarn.lock

- feat(participant-card): creating ParticipantCard

feat(participant-card): creating ParticipantCard

---

apps/codeet-next/app/(events)/events/[eventId]/loading.tsx
apps/codeet-next/app/(events)/events/loading.tsx
apps/codeet-next/app/(groups)/groups/loading.tsx
apps/codeet-next/components/event-card.tsx
apps/codeet-next/components/group-card.tsx
apps/codeet-next/components/ui/skeleton.tsx

- feat(loading): adding loading on pages

feat(loading): adding loading on pages
